#!/usr/bin/env bash
# patches vencord with the stuff equicord plugins need.
# runs after pnpm install, before pnpm buildWeb.
# called automatically by build-vencord.sh — set VENCORD_DIR before running manually.
set -euo pipefail

VENCORD_DIR="${VENCORD_DIR:?VENCORD_DIR must be set}"

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'
info()    { echo -e "${CYAN}${BOLD}[patch]${RESET} $*"; }
success() { echo -e "${GREEN}${BOLD}[patch ✓]${RESET} $*"; }
warn()    { echo -e "\033[0;33m${BOLD}[patch ⚠]${RESET} $*"; }
die()     { echo -e "${RED}${BOLD}[patch ✗]${RESET} $*" >&2; exit 1; }

# 1. equicorddevs shim — lets equicord plugins reference authors without breaking the build
info "injecting EquicordDevs shim into @utils/constants..."

CONSTANTS="$VENCORD_DIR/src/utils/constants.ts"
[[ -f "$CONSTANTS" ]] || die "constants.ts not found at $CONSTANTS"

if ! grep -q "EquicordDevs" "$CONSTANTS"; then
    cat >> "$CONSTANTS" << 'EOF'

// vendrix: equicorddevs shim
// makes equicord plugins compile on vanilla vencord — looks up from Devs first,
// falls back to a placeholder if the name isn't there.
export const EquicordDevs: Record<string, Dev> = new Proxy({} as Record<string, Dev>, {
    get(_, prop: string): Dev {
        const match = Object.values(Devs).find((d: Dev) => d.name === prop);
        return match ?? { name: String(prop), id: 0n };
    }
});
EOF
    success "EquicordDevs shim injected"
else
    info "EquicordDevs already present, skipping"
fi

# 2. managedstyle vite plugin — handles ?managed css imports used by equicord plugins
info "injecting managedStyle Vite plugin..."

# drop the plugin module into vencord's vite scripts folder
PLUGIN_FILE="$VENCORD_DIR/scripts/vite/vendrixManagedStyle.mts"
mkdir -p "$(dirname "$PLUGIN_FILE")"

cat > "$PLUGIN_FILE" << 'EOF'
// vendrix: handles `?managed` css imports from equicord-style plugins.
// instead of inlining css at build time, returns a runtime object with
// enable() / disable() that injects or removes a <style> tag.
import { readFileSync } from "fs";
import type { Plugin } from "vite";

export function vendrixManagedStyle(): Plugin {
    return {
        name: "vendrix:managed-style",
        enforce: "pre",
        resolveId(id: string) {
            if (id.endsWith("?managed")) return id;
        },
        load(id: string) {
            if (!id.endsWith("?managed")) return;

            const realPath = id.slice(0, -"?managed".length);
            let css = "";
            try { css = readFileSync(realPath, "utf-8"); } catch { /* file missing, use empty */ }

            const escaped = css
                .replace(/\\/g, "\\\\")
                .replace(/`/g, "\\`")
                .replace(/\$\{/g, "\\${");

            return `
const css = \`${escaped}\`;
let el = null;
export default {
    css,
    enable()  { if (el) return; el = Object.assign(document.createElement("style"), { textContent: css }); document.head.appendChild(el); },
    disable() { el?.remove(); el = null; }
};`;
        }
    };
}
EOF

# find every vite config in the repo and patch each one
PATCHED=0
while IFS= read -r cfg; do
    if grep -q "vendrixManagedStyle\|vendrix:managed-style" "$cfg" 2>/dev/null; then
        info "  already patched: $cfg"
        continue
    fi

    # figure out the relative path from this config to the plugin module
    CFG_DIR="$(dirname "$cfg")"
    REL=$(python3 -c "import os.path; print(os.path.relpath('$PLUGIN_FILE', '$CFG_DIR'))" 2>/dev/null \
        || node -e "const p=require('path');process.stdout.write(p.relative('$CFG_DIR','$PLUGIN_FILE'))")

    node << JSEOF
const fs = require("fs");
const cfgPath = "$cfg";
const relPlugin = "./${REL}".replace(/\\.mts$/, ".mjs");
let src = fs.readFileSync(cfgPath, "utf-8");

// add the import at the top
const importLine = \`import { vendrixManagedStyle } from "\${relPlugin}";\n\`;
if (!src.includes("vendrixManagedStyle")) {
    src = importLine + src;
}

// inject into the plugins array
if (src.includes("plugins:") && !src.includes("vendrixManagedStyle()")) {
    src = src.replace(/(plugins\s*:\s*\[)/, "\$1\n        vendrixManagedStyle(),");
}

fs.writeFileSync(cfgPath, src);
console.log("  patched: $cfg");
JSEOF
    PATCHED=$((PATCHED + 1))
done < <(find "$VENCORD_DIR" -maxdepth 3 \( \
    -name "*.vite.config.mts" \
    -o -name "*.vite.config.ts" \
    -o -name "vite.config.mts" \
    -o -name "vite.config.ts" \
    -o -name "vite.config.mjs" \
    -o -name "vite.config.js" \
\) 2>/dev/null)

if [[ $PATCHED -eq 0 ]]; then
    # couldn't find any vite config — css will still work, just won't be togglable
    warn "no vite config found — css from ?managed imports will be statically inlined, enable/disable will be no-ops"

    SHIM="$VENCORD_DIR/src/plugins/_vendrix_managed_shim.ts"
    cat > "$SHIM" << 'EOF'
// vendrix shim — placeholder so ?managed imports don't cause a build error.
// auto-generated by apply-patches.sh, do not edit.
EOF
fi

if [[ $PATCHED -gt 0 ]]; then
    success "managedStyle plugin injected into $PATCHED vite config(s)"
fi

# 3. audioplayer api — vanilla vencord doesn't have this at all, so we create it from scratch
info "creating AudioPlayer API..."

AUDIO_PLAYER="$VENCORD_DIR/src/api/AudioPlayer.ts"
API_INDEX="$VENCORD_DIR/src/api/index.ts"

if ! grep -q "createAudioPlayer" "$AUDIO_PLAYER" 2>/dev/null; then
    cat > "$AUDIO_PLAYER" << 'EOF'
// vendrix: full AudioPlayer API shim
// vanilla vencord doesn't ship this — we create it so equicord plugins that import
// from @api/AudioPlayer work without changes.

import { findByPropsLazy } from "@webpack";

// grab discord's internal sound player
const SoundUtils = findByPropsLazy("playSound", "createSound");

export interface AudioPlayerInterface {
    play(): void;
    stop(): void;
    readonly sound: string;
}

export interface CreateAudioPlayerOptions {
    volume?: number;
    onEnded?: () => void; // fires when the sound finishes naturally (not on manual stop)
}

const KNOWN_AUDIO_NAMES = [
    "bop_message1","bop_message2","bop_message3",
    "call_calling","call_ringing","call_ringing_beat",
    "deafen","discodo","disconnect","high_five","human_man","interact",
    "in_call_text_message","mention1","mention2","mention3","mute",
    "navigation_backdrop_1","navigation_backdrop_2","overlapping_boop",
    "outgoing_ring","ptt_start","ptt_stop","reconnect","request_to_speak",
    "stream_started","stream_user_joined","stream_user_left",
    "subtle_1","subtle_2","undeafen","unmute","vibing_wumpus",
    "window_open","window_close","wumpus_tune",
] as const;

// returns all known discord notification sound names — used for dropdowns etc.
export function defaultAudioNames(): string[] {
    return [...KNOWN_AUDIO_NAMES];
}

// plays a sound by name at the given volume (0–100)
export function playAudio(sound: string, options: { volume?: number; } = {}): Promise<void> {
    return new Promise(resolve => {
        try {
            SoundUtils.playSound(sound, (options.volume ?? 100) / 100);
        } catch { /* sound not found or module not ready */ }
        resolve();
    });
}

// creates a controllable player with play/stop lifecycle
export function createAudioPlayer(sound: string, options: CreateAudioPlayerOptions = {}): AudioPlayerInterface {
    let stopped = false;
    return {
        sound,
        play() {
            if (stopped) return;
            playAudio(sound, { volume: options.volume ?? 100 })
                .then(() => { if (!stopped) options.onEnded?.(); })
                .catch(() => {});
        },
        stop() { stopped = true; }
    };
}
EOF
    success "AudioPlayer API created"
else
    info "AudioPlayer already has createAudioPlayer, skipping"
fi

# make sure the api index exports it so @api/AudioPlayer resolves correctly
if [[ -f "$API_INDEX" ]] && ! grep -q "AudioPlayer" "$API_INDEX"; then
    echo 'export * from "./AudioPlayer";' >> "$API_INDEX"
    success "AudioPlayer registered in api/index.ts"
fi

# register AudioPlayerAPI as a known plugin dependency if the type exists
TYPES_FILE="$VENCORD_DIR/src/utils/types.ts"
if [[ -f "$TYPES_FILE" ]] && ! grep -q "AudioPlayerAPI" "$TYPES_FILE"; then
    sed -i 's/\(type PluginDependency = \)\(.*\)$/\1"AudioPlayerAPI" | \2/' "$TYPES_FILE" 2>/dev/null || true
fi

echo ""
echo -e "${GREEN}${BOLD}all patches applied.${RESET}"
d manually). */
    onEnded?: () => void;
}

/**
 * Creates a controllable audio player for a given sound name.
 * Wraps playAudio() with play/stop lifecycle management.
 */
export function createAudioPlayer(sound: string, options: CreateAudioPlayerOptions = {}): AudioPlayerInterface {
    let stopped = false;
    let resolvePlay: (() => void) | null = null;

    return {
        sound,
        play() {
            if (stopped) return;
            playAudio(sound, {
                volume: options.volume ?? 100,
            }).then(() => {
                if (!stopped) {
                    options.onEnded?.();
                }
                resolvePlay?.();
            }).catch(() => {
                resolvePlay?.();
            });
        },
        stop() {
            stopped = true;
            resolvePlay?.();
            // playAudio doesn't expose a cancel API in vanilla Vencord,
            // so we just mark as stopped and suppress the onEnded callback.
        }
    };
}
EOF
    success "AudioPlayer extensions injected"
else
    info "AudioPlayer extensions already present, skipping"
fi

echo ""
echo -e "${GREEN}${BOLD}All Vendrix patches applied successfully.${RESET}"
